endpoints:
  info: https://global-prod.disco-api.com/bootstrapInfo
  user: "{base_api}/users/me"
  prod: "{base_api}/cms/configs/web-prod"
  show: "{base_api}/cms/routes/show/{title_id}?include=default&decorators=viewingHistory,isFavorite,playbackAllowed"
  seasons: "{base_api}/cms/collections/{content_id}?include=default&decorators=viewingHistory,isFavorite,playbackAllowed,contentAction,badges&{season}&{show_id}"
  playback: "{base_api}/playback/v3/videoPlaybackInfo"
  search: "{base_api}/cms/routes/search/result?include=default&decorators=viewingHistory,isFavorite,playbackAllowed,contentAction,badges&contentFilter[query]={query}&page[items.number]=1&page[items.size]=8"