headers:
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0
  accept-language: en-US,en;q=0.8

endpoints:
  login: https://auth.prd.user.itv.com/v2/auth
  refresh: https://auth.prd.user.itv.com/token
  search: https://textsearch.prd.oasvc.itv.com/search